[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    imgSrc = "'self' data:;"
    styleSrc = "'self' 'unsafe-inline'"
    styleSrcElem = "'self'"
    scriptSrc = "'self'"
