[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    imgSrc = "'self' data:;"
    fontSrc = "'self' data:;"
    styleSrc = "'unsafe-hashes' 'unsafe-inline' 'sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY=' 'sha256-fffcGhUhmnLFE3nBYvjR5eHJYzWK2vVaG/L3mbkZXBA='"
    styleSrcElem = "'self' 'unsafe-inline'"
    scriptSrc = "'self' 'unsafe-eval' https://cloud.issabel.org/click2call/click.js https://cloud.issabel.org/click2call/aes.js 'sha256-6egcWvmQP5hRCmW3iDq1X7sXo3/AY4zjQJNgqpm0rAg='" 
    frameSrc = "https://cloud.issabel.org/"
    connectSrc =  "'self' https://latam-be.herokuapp.com/pagos"
