[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    imgSrc = "'self' data:;"
    fontSrc = "'self' data:;"
    styleSrc = "'self' 'unsafe-hashes' 'sha256-0EZqoz+oBhx7gF4nvY2bSqoGyy4zLjNF+SDQXGp/ZrY=' 'sha256-fffcGhUhmnLFE3nBYvjR5eHJYzWK2vVaG/L3mbkZXBA=' 'sha256-To2kn4dvA1DVwPuSF7+540sjDqZStfK+C0qQGoST7Ik='"
    styleSrcElem = "'self'"
    scriptSrc = "'self' 'unsafe-eval'"
    scriptSrcElem = "'self' 'unsafe-inline' cloud.issabel.org"

