[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    imgSrc = "'self'"
    styleSrc = "'self'"
    styleSrcElem = "'self'"
    scriptSrc = "'self'"
