export const deportivos = [
  { image: '/canales/deportes/claro_sports_logo.webp' },
  { image: '/canales/deportes/discovery_turbo_logo.webp' },
  { image: '/canales/deportes/espn_2_logo.webp' },
  { image: '/canales/deportes/espn_3_logo.webp' },
  { image: '/canales/deportes/espn_logo.webp' },
  { image: '/canales/deportes/fox_sports_1_logo.webp' },
  { image: '/canales/deportes/fox_sports_2_logo.webp' },
  { image: '/canales/deportes/fox_sports_3_logo.webp' },
  { image: '/canales/deportes/ivc_logo.webp' },
  { image: '/canales/deportes/meridiano_tv_logo.webp' },
];

export const internacionales = [
  { image: '/canales/familiares/comedy_central_logo.webp' },
  { image: '/canales/familiares/enlace_logo.webp' },
  { image: '/canales/familiares/isat_logo.webp' },
  { image: '/canales/familiares/las_estrellas_logo.webp' },
  { image: '/canales/familiares/telemundo_logo.webp' },
  { image: '/canales/familiares/telenovelas_logo.webp' },
  { image: '/canales/familiares/tru_tv_logo.webp' },
  { image: '/canales/familiares/venevision_plus_logo.webp' },
  { image: '/canales/internacionales/antena3_logo.webp' },
  { image: '/canales/internacionales/cctv_logo.webp' },
  { image: '/canales/internacionales/ewtn_logo.webp' },
  { image: '/canales/internacionales/rtp_logo.webp' },
  { image: '/canales/internacionales/televisión_de_galicia_logo.webp' },
  { image: '/canales/internacionales/tv_peru_logo.webp' },
  { image: '/canales/internacionales/tve_24h_logo.webp' },
  { image: '/canales/internacionales/tve_logo.webp' },
];

export const infantiles = [
  { image: '/canales/infantiles/baby_tv_logo.webp' },
  { image: '/canales/infantiles/boomerang_logo.webp' },
  { image: '/canales/infantiles/cartoon_network_logo.webp' },
  { image: '/canales/infantiles/discovery_kids_logo.webp' },
  { image: '/canales/infantiles/disney_channel_logo.webp' },
  { image: '/canales/infantiles/disney_junior_logo.webp' },
  { image: '/canales/infantiles/disney_xd_logo.webp' },
  { image: '/canales/infantiles/nickelodeon_logo.webp' },
  { image: '/canales/infantiles/tooncast_logo.webp' },
];

export const nacionales = [
  { image: '/canales/nacionales/antv_logo.webp' },
  { image: '/canales/nacionales/colombeia_tv_logo.webp' },
  { image: '/canales/nacionales/conciencia_logo.webp' },
  { image: '/canales/nacionales/corazon_llanero_logo.webp' },
  { image: '/canales/nacionales/globovision_logo.webp' },
  { image: '/canales/nacionales/telesur_logo.webp' },
  { image: '/canales/nacionales/televen_logo.webp' },
  { image: '/canales/nacionales/tlt_logo.webp' },
  { image: '/canales/nacionales/tv_fanb_logo.webp' },
  { image: '/canales/nacionales/tves.webp' },
  { image: '/canales/nacionales/venevision_logo.webp' },
  { image: '/canales/nacionales/vive_logo.webp' },
  { image: '/canales/nacionales/vtv_logo.webp' },
];

export const syp = [
  { image: '/canales/syp/axn_channel_logo.webp' },
  { image: '/canales/syp/cinecanal_logo.webp' },
  { image: '/canales/syp/cinelatino_logo.webp' },
  { image: '/canales/syp/citytv_logo.webp' },
  { image: '/canales/syp/de_pelicula_logo.webp' },
  { image: '/canales/syp/fox_action_logo.webp' },
  { image: '/canales/syp/fox_channel_logo.webp' },
  { image: '/canales/syp/fox_cinema_logo.webp' },
  { image: '/canales/syp/fx_international_logo.webp' },
  { image: '/canales/syp/fx_movies_logo.webp' },
  { image: '/canales/syp/golden_logo.webp' },
  { image: '/canales/syp/multipremier_logo.webp' },
  { image: '/canales/syp/paramount_logo.webp' },
  { image: '/canales/syp/sony_channel_logo.webp' },
  { image: '/canales/syp/space_logo.webp' },
  { image: '/canales/syp/studio_universal_logo.webp' },
  { image: '/canales/syp/syfy_logo.webp' },
  { image: '/canales/syp/tbs_logo.webp' },
  { image: '/canales/syp/tcm_logo.webp' },
  { image: '/canales/syp/tnt_logo.webp' },
  { image: '/canales/syp/tnt_series_logo.webp' },
  { image: '/canales/syp/universal_tv_logo.webp' },
  { image: '/canales/syp/warner_channel_logo.webp' },
];

export const variedades = [
  { image: '/canales/variedades/animal_planet_logo.webp' },
  { image: '/canales/variedades/discovery_home_and_health_logo.webp' },
  { image: '/canales/variedades/discovery_id_logo.webp' },
  { image: '/canales/variedades/discovery_logo.webp' },
  { image: '/canales/variedades/glitz_logo.webp' },
  { image: '/canales/variedades/nat_geo_wild_logo.webp' },
  { image: '/canales/variedades/natgeo_kids_logo.webp' },
  { image: '/canales/variedades/national_geographic_logo.webp' },
  { image: '/canales/variedades/tlc_logo.webp' },
  { image: '/canales/musicales/htv_logo.webp' },
  { image: '/canales/musicales/mtv_logo.webp' },
  { image: '/canales/musicales/telehit_logo.webp' },
];

export default {
  deportivos,
  internacionales,
  infantiles,
  nacionales,
  syp,
  variedades,
};
