export const deportivos = [
  { image: "/canales/deportes/claro_sports_logo.png" },
  { image: "/canales/deportes/discovery_turbo_logo.png" },
  { image: "/canales/deportes/espn_2_logo.png" },
  { image: "/canales/deportes/espn_3_logo.png" },
  { image: "/canales/deportes/espn_logo.png" },
  { image: "/canales/deportes/fox_sports_1_logo.png" },
  { image: "/canales/deportes/fox_sports_2_logo.png" },
  { image: "/canales/deportes/fox_sports_3_logo.png" },
  { image: "/canales/deportes/ivc_logo.png" },
  { image: "/canales/deportes/meridiano_tv_logo.png" },
];

export const internacionales = [
  { image: "/canales/familiares/comedy_central_logo.png" },
  { image: "/canales/familiares/enlace_logo.png" },
  { image: "/canales/familiares/isat_logo.png" },
  { image: "/canales/familiares/las_estrellas_logo.png" },
  { image: "/canales/familiares/telemundo_logo.png" },
  { image: "/canales/familiares/telenovelas_logo.png" },
  { image: "/canales/familiares/tru_tv_logo.png" },
  { image: "/canales/familiares/venevision_plus_logo.png" },
  { image: "/canales/internacionales/antena3_logo.png" },
  { image: "/canales/internacionales/cctv_logo.png" },
  { image: "/canales/internacionales/ewtn_logo.png" },
  { image: "/canales/internacionales/rtp_logo.png" },
  { image: "/canales/internacionales/televisión_de_galicia_logo.png" },
  { image: "/canales/internacionales/tv_peru_logo.png" },
  { image: "/canales/internacionales/tve_24h_logo.png" },
  { image: "/canales/internacionales/tve_logo.png" },
];

export const infantiles = [
  { image: "/canales/infantiles/baby_tv_logo.png" },
  { image: "/canales/infantiles/boomerang_logo.png" },
  { image: "/canales/infantiles/cartoon_network_logo.png" },
  { image: "/canales/infantiles/discovery_kids_logo.png" },
  { image: "/canales/infantiles/disney_channel_logo.png" },
  { image: "/canales/infantiles/disney_junior_logo.png" },
  { image: "/canales/infantiles/disney_xd_logo.png" },
  { image: "/canales/infantiles/nickelodeon_logo.png" },
  { image: "/canales/infantiles/tooncast_logo.png" },
];

export const nacionales = [
  { image: "/canales/nacionales/antv_logo.png" },
  { image: "/canales/nacionales/colombeia_tv_logo.png" },
  { image: "/canales/nacionales/conciencia_logo.png" },
  { image: "/canales/nacionales/corazon_llanero_logo.png" },
  { image: "/canales/nacionales/globovision_logo.png" },
  { image: "/canales/nacionales/telesur_logo.png" },
  { image: "/canales/nacionales/televen_logo.png" },
  { image: "/canales/nacionales/tlt_logo.png" },
  { image: "/canales/nacionales/tv_fanb_logo.png" },
  { image: "/canales/nacionales/tves.png" },
  { image: "/canales/nacionales/venevision_logo.png" },
  { image: "/canales/nacionales/vive_logo.png" },
  { image: "/canales/nacionales/vtv_logo.png" },
];

export const syp = [
  { image: "/canales/syp/axn_channel_logo.png" },
  { image: "/canales/syp/cinecanal_logo.png" },
  { image: "/canales/syp/cinelatino_logo.png" },
  { image: "/canales/syp/citytv_logo.png" },
  { image: "/canales/syp/de_pelicula_logo.png" },
  { image: "/canales/syp/fox_action_logo.png" },
  { image: "/canales/syp/fox_channel_logo.png" },
  { image: "/canales/syp/fox_cinema_logo.png" },
  { image: "/canales/syp/fx_international_logo.png" },
  { image: "/canales/syp/fx_movies_logo.png" },
  { image: "/canales/syp/golden_logo.png" },
  { image: "/canales/syp/multipremier_logo.png" },
  { image: "/canales/syp/paramount_logo.png" },
  { image: "/canales/syp/sony_channel_logo.png" },
  { image: "/canales/syp/space_logo.png" },
  { image: "/canales/syp/studio_universal_logo.png" },
  { image: "/canales/syp/syfy_logo.png" },
  { image: "/canales/syp/tbs_logo.png" },
  { image: "/canales/syp/tcm_logo.png" },
  { image: "/canales/syp/tnt_logo.png" },
  { image: "/canales/syp/tnt_series_logo.png" },
  { image: "/canales/syp/universal_tv_logo.png" },
  { image: "/canales/syp/warner_channel_logo.png" },
];

export const variedades = [
  { image: "/canales/variedades/animal_planet_logo.png" },
  { image: "/canales/variedades/discovery_home_and_health_logo.png" },
  { image: "/canales/variedades/discovery_id_logo.png" },
  { image: "/canales/variedades/discovery_logo.png" },
  { image: "/canales/variedades/glitz_logo.png" },
  { image: "/canales/variedades/nat_geo_wild_logo.png" },
  { image: "/canales/variedades/natgeo_kids_logo.png" },
  { image: "/canales/variedades/national_geographic_logo.png" },
  { image: "/canales/variedades/tlc_logo.png" },
  { image: "/canales/musicales/htv_logo.png" },
  { image: "/canales/musicales/mtv_logo.png" },
  { image: "/canales/musicales/telehit_logo.png" },
];

export default (deportivos,
internacionales,
infantiles,
nacionales,
syp,
variedades);
